import { Fruit, dataBaseFruits } from './fruitsService.js';

/*################
### Insertions ###
################*/

/**
 * Fill the database with default information
 */
export default function () {

    let coco = new Fruit("Coco", "/imagenes/coco.jpg", 2.25, "Indonesia", "Invierno", "Fruta", "Fruto del coco, que es de la forma y tamaño de un melón regular, cubierto de dos cortezas, al modo que la nuez, la primera fibrosa y la segunda muy dura; por dentro y adherida a esta tiene una pulpa blanca y gustosa, y en la cavidad central un líquido refrigerante. Con la primera corteza se hacen cuerdas y tejidos bastos; con la segunda, tazas, vasos y otros utensilios; de la carne se hacen dulces y se saca aceite.", new Set(["Vitamina C", "Vitamina E", "Vitamina B1", "Vitamina B2", "Fósforo", "Potasio", "Magnesio", "Hierro", "Vitamina B3", "Vitamina B5", "Vitamina B6", "Vitamina B9", "Calcio", "Zinc"]));
    let platano = new Fruit("Plátano", "/imagenes/platano.jpg", 2.69, "España", "Primavera", "Fruta", "Es un fruto con cualidades variables en tamaño, color y firmeza, alargado, generalmente curvado y carnoso, rico en almidón cubierto con una cáscara, que puede ser verde, amarilla, roja, púrpura o marrón cuando está madura. Los frutos crecen en piñas que cuelgan de la parte superior de la planta. Casi todos los plátanos en la actualidad son frutos estériles que no producen semillas fructificantes y provienen de dos especies silvestres: Musa acuminata y Musa balbisiana. El nombre científico de la mayoría de los plátanos cultivados es Musa × paradisiaca, el híbrido Musa acuminata × M. balbisiana, con distintas denominaciones var. o cultivares, dependiendo de su constitución genómica.", new Set(["Vitamina A", "Vitamina E", "Vitamina B1", "Vitamina B2", "Fósforo", "Potasio", "Magnesio", "Hierro", "Vitamina B3", "Vitamina B5", "Vitamina B6", "Vitamina B9", "Calcio", "Zinc", "Cobre", "Manganeso", "Flúor", "Selenio", "Sodio", "Vitamina 12", "Vitaminda C", "Vitaminda D", "Vitaminda K"]));
    let naranja = new Fruit("Naranja", "/imagenes/naranja.jpg", 1.35, "Brasil", "Primavera", "Fruta", "La naranja es la fruta cítrica del naranjo (Citrus aurantium), con dos subespecies principales: el naranjo dulce (subespecie Sinensis) y agrio (subespecie Amara). Se la denomina cítrica por su contenido en ácido cítrico, que le confiere el sabor amargo. El naranjo es un árbol de una altura comprendida entre 3 y 10 metros, de tallo ligeramente espinoso, hoja perenne y flor blanca, muy aromática, la flor de azahar. La naranja es un fruto hesperidio (pulpa carnosa entre el endocarpio y las semillas en forma de gajos llenos de zumo), de corteza lisa y más o menos endurecida con vesículas oleosas. Tiene sabor dulce o ligeramente agrio, dependiendo de la variedad.", new Set(["Agua", "Energía", "Grasa", "Proteína", "Hidratos de carbono", "Fibra", "Potasio", "Fósforo", "Hierro", "Sodio", "Magnesio", "Calcio", "Cobre", "Zinc", "Manganeso", "Vitamina C", "Vitamina A", "Vitamina B1", "Vitamina B2", "Vitamina B3", "Vitamina E", "Vitamina B6", "Ácido fólico"]));
    let fresa = new Fruit("Fresa", "/imagenes/fresa.jpg", 3, "Estados Unidos", "Primavera", "Fruta", "Son plantas herbáceas, perennifolias, con rizomas y estolones epigeos más o menos desarrollados, que enraízan en los nudos donde nacen hojas arrosetadas tri-partidas. Los tallos son generalmente simples, más o menos erectos y anuales. Las hojas se agrupan en falsas rosetas, con los segmentos ovalo-rómbicos, distalmente dentados. Las inflorescencias se organizan en cimas con brácteas. Las flores, hermafroditas o funcionalmente unisexuales, tienen un receptáculo con la zona axial algo cónica, acrescente y carnosa en la fructificación. Los 5 sépalos son lanceolados y en general enteros, más o menos acrescentes, erectos, patentes o reflejos en la fructificación. El calículo tiene 5 piezas más estrechas que los sépalos y son usualmente enteros. Los pétalos, en general en número de 5, son habitualmente mayores que los sépalos; son obovados, no escotados, con la uña corta, blancos, blanco-verdosos o de color crema. Hay unos 10-20 estambres y numerosos carpelos libres implantados en la zona axial del receptáculo. El fruto es un poliaquenio de aquenios ovoides incrustados en dicho receptáculo (eterio) que se vuelve carnoso al madurar.", new Set(["Proteínas", "Hidratos de carbono", "Fibra", "Agua", "Calcio", "Hierro", "Yodo", "Magnesio", "Zinc", "Sodio", "Potasio", "Fósforo", "Selenio", "Tiamina", "Riboflavina", "Vitamina B", "Folatos", "Vitamina B12", "Vitamina C", "Vitamina A", "Vitamina D", "Vitamina E"]));
    let kiwi = new Fruit("Kiwi", "/imagenes/kiwi.jpg", 2.35, "Italia", "Invierno", "Fruta", "Es una baya oval de unos 6 cm de largo, con piel delgada de color verde parduzco y densamente cubierta de unos pelillos rígidos y cortos de color marrón. La pulpa, firme hasta que madura completamente, es de color verde brillante jugosa y con diminutas semillas negras dispuestas en torno a un corazón blanquecino. Tiene un sabor de subácido a bastante ácido, similar al de la grosella o la fresa.2​ Suele ser un alérgeno frecuente, sobre todo su piel.", new Set(["Proteínas", "Hidratos de carbono", "Fibra", "Agua", "Calcio", "Hierro", "Yodo", "Magnesio", "Zinc", "Sodio", "Potasio", "Fósforo", "Selenio", "Tiamina", "Riboflavina", "Vitamina B", "Folatos", "Vitamina B12", "Vitamina C", "Vitamina A", "Vitamina D", "Vitamina E"]));

    dataBaseFruits.set(coco.getName(), coco);
    dataBaseFruits.set(platano.getName(), platano);
    dataBaseFruits.set(naranja.getName(), naranja);
    dataBaseFruits.set(fresa.getName(), fresa);
    dataBaseFruits.set(kiwi.getName(), kiwi);

    let pera = new Fruit("Pera", "/imagenes/pera.jpg", 1.79, "China", "Otoño", "Fruta", "Se denomina pera al fruto de distintas especies del género Pyrus, integrado por árboles caducifolios conocidos comúnmente como perales.1​ Sin embargo, cuando se trata del fruto comestible, se hace referencia mayormente al producido por el llamado peral común (Pyrus communis). La pera es una fruta muy jugosa, carnosa y una de las más importantes producidas en las regiones templadas.", new Set(["Proteínas", "Hidratos de carbono", "Fibra", "Agua", "Calcio", "Hierro", "Yodo", "Magnesio", "Zinc", "Sodio", "Potasio", "Fósforo", "Selenio", "Tiamina", "Riboflavina", "Vitamina B", "Folatos", "Vitamina B12", "Vitamina C", "Vitamina A", "Vitamina D", "Vitamina E"]));
    let zanahoria = new Fruit("Zanahoria", "/imagenes/zanahoria.jpg", 0.89, "China", "Invierno", "Verdura", "Planta bienal que forma una roseta de hojas en otoño e invierno, mientras desarrolla la fina raíz napiforme, la cual almacenará grandes cantidades de azúcar para la floración del año siguiente. El tallo floral crece alrededor de 10 cm con una umbela de flores blancas en el ápice. La raíz comestible suele ser de color naranja y negra o en una combinación de estas, e incluso -más raramente- de cáscara violeta con un interior blancuzco.", new Set(["Proteínas", "Hidratos de carbono", "Fibra", "Agua", "Calcio", "Hierro", "Yodo", "Magnesio", "Zinc", "Sodio", "Potasio", "Fósforo", "Selenio", "Tiamina", "Riboflavina", "Vitamina B", "Folatos", "Vitamina B12", "Vitamina C", "Vitamina A", "Vitamina D", "Vitamina E"]));
    let tomate = new Fruit("Tomate", "/imagenes/tomate.jpg", 2.19, "Turquía", "Otoño", "Fruta", "El tomate1​ o jitomate (en algunas partes de México)2​ es el fruto de la planta Solanum lycopersicum, el cual tiene importancia culinaria y es utilizado como verdura. Siendo el tomate una fruta botánicamente clasificado como una baya, es comúnmente usado en arte culinario como un ingrediente vegetal o guarnición", new Set(["Proteínas", "Hidratos de carbono", "Fibra", "Agua", "Calcio", "Hierro", "Yodo", "Magnesio", "Zinc", "Sodio", "Potasio", "Fósforo", "Selenio", "Tiamina", "Riboflavina", "Vitamina B", "Folatos", "Vitamina B12", "Vitamina C", "Vitamina A", "Vitamina D", "Vitamina E"]));
    let patata = new Fruit("Patata", "/imagenes/patata.jpg", 2, "Polonia", "Primavera", "Verdura", "La patata es un tubérculo perteneciente a la familia Solanaceae, cuyo nombre científico es Solanum tuberosum. Es planta herbácea provista de un sistema aéreo y otro subterráneo de naturaleza rizomatosa del cual se originan los tubérculos, donde se acumulan las reservas de almidón.", new Set(["Potasio", "Vitamina C", "Magnesio", "Fósforo", "Calcio", "Hierro", "Zinc", "Vitamina B1", "Vitamina B3", "Vitamina B6"]));
    let espinacas = new Fruit("Espinacas", "/imagenes/espinacas.jpg", 1.60, "Japón", "Primavera", "Verdura", "La espinaca (Spinacia oleracea) es una planta anual, dioica, de la familia de las amarantáceas, cultivada como verdura por sus hojas comestibles, grandes y de color verde muy oscuro. Su cultivo se puede realizar en cualquier época del año y se puede consumir fresca, cocida o frita. En la actualidad es una de las verduras que más habitualmente se encuentra helada o congelada", new Set(["Proteínas", "Hidratos de carbono", "Fibra", "Agua", "Calcio", "Hierro", "Yodo", "Magnesio", "Zinc", "Sodio", "Potasio", "Fósforo", "Selenio", "Tiamina", "Riboflavina", "Vitamina B", "Folatos", "Vitamina B12", "Vitamina C", "Vitamina A", "Vitamina D", "Vitamina E"]));

    dataBaseFruits.set(pera.getName(), pera);
    dataBaseFruits.set(zanahoria.getName(), zanahoria);
    dataBaseFruits.set(tomate.getName(), tomate);
    dataBaseFruits.set(patata.getName(), patata);
    dataBaseFruits.set(espinacas.getName(), espinacas);

    let judias = new Fruit("Judías", "/imagenes/judias.jpg", 2, "Sudáfrica", "Verano", "Verdura", "Es una planta herbácea que presenta su legumbre en más de 50 variedades de diversos tamaños y colores. Es originaria de América central y América del Sur, nativa de Mesoamérica (México, Guatemala, Honduras y El Salvador),14​ floración anual, trepadora, de tallo pubescente o glabrescente cuando llega a la edad adulta. Las estípulas de las hojas tri-pinnadas son de forma lanceolada y de tamaño medio-centimétrico. Los folíolos son anchamente ovados u ovado-romboidal, los laterales, implantados oblicuamente, miden 4-15 por 2,5-10 cm y son pubescentes con base redondeada o anchamente cuneada, de bordes enteros y ápice acuminado. Las flores se disponen en racimos usualmente axilares, más cortos que las hojas. Las bractéolas, persistentes, son habitualmente de longitud igual o algo superior al cáliz que es cupuliforme, bilabiado, de 3-4 mm, con cinco sépalos soldados y con el labio superior bidentado emarginado y el inferior tridentado. La corola, que puede ser blanca, amarilla, violácea o roja, tiene el estandarte centimétrico suborbicular y reflejo, las alas obovadas adheridas a la quilla, también centimétrica y con ápice espiralmente retorcido. Los estambres son diadelfos (9 soldados y 1 libre) mientras que el ovario es pubescente con el estilo espiralmente torcido de 360º o más y con estigma oblicuo. Dicho gineceo deriva en una legumbre lineal-oblonga de unos 10-15 por 1-1,5 cm, algo curvada e hinchada, glabra, picuda y con cuatro a diez semillas oblongas arriñonadas de muy diversos colores y tamaños, usualmente 1-2 por 0,5-1,5 cm.", new Set(["Proteínas", "Hidratos de carbono", "Fibra", "Agua", "Calcio", "Hierro", "Yodo", "Magnesio", "Zinc", "Sodio", "Potasio", "Fósforo", "Selenio", "Tiamina", "Riboflavina", "Vitamina B", "Folatos", "Vitamina B12", "Vitamina C", "Vitamina A", "Vitamina D", "Vitamina E"]));
    let calabacin = new Fruit("Calabacín", "/imagenes/calabacin.jpg", 1.99, "India", "Verano", "Fruta", "Cucurbita pepo es el nombre científico de una especie de plantas cucurbitáceas originaria de Mesoamérica y sur de Estados Unidos, que junto con otras especies emparentadas (Cucurbita maxima, C. moschata, C. argyrosperma) forman un grupo de especies de calabazas cuyas variedades cultivadas, de las que se cosecha su fruto maduro o inmaduro, poseen usos culinarios indistinguibles (son los zapallos, calabacines, zapallitos, zapallo americano, auyamas, ahuyamas, pipianes, ayotes, etc). En su región de origen posee variedades silvestres (Cucurbita pepo fraterna,2​3​ Cucurbita pepo var. texana,2​3​ Cucurbita pepo var. ozarkana;2​3​ las 3 podrían ser encontradas bajo un nombre binomial: Cucurbita fraterna, C. texana, C. ozarkana) de las que incluso desde varios kilómetros puede llegar el polen a las variedades cultivadas de su propia especie haciendo que sus semillas se desarrollen como plantas de frutos amargos y no comestibles. No hibrida con las demás especies.", new Set(["Proteínas", "Hidratos de carbono", "Fibra", "Agua", "Calcio", "Hierro", "Yodo", "Magnesio", "Zinc", "Sodio", "Potasio", "Fósforo", "Selenio", "Tiamina", "Riboflavina", "Vitamina B", "Folatos", "Vitamina B12", "Vitamina C", "Vitamina A", "Vitamina D", "Vitamina E"]));
    let calabaza = new Fruit("Calabaza", "/imagenes/calabaza.jpg", 1.15, "India", "Verano", "Fruta", "La calabaza es una baya de cáscara dura. Es el fruto de las cucurbitáceas (del género Cucurbita) y es un fruto de tipo pepónide. Algunos autores también incluyen a los frutos del género Lagenaria, y a los frutos de las plantas de la familia de las bignoniáceas, como los árboles de calabazas Crescentia y Amphitecna. Las calabazas se encuentran tanto de manera silvestre como cultivada. Las calabazas, incluidas las silvestres, son de tamaño grande, de más de 5 cm de diámetro.1​ Presentan una gran variedad de formas, tamaños, texturas, sabores y colores. Los frutos se pueden cosechar tanto maduros como inmaduros, dependiendo del uso final que se le de al fruto.", new Set(["Proteínas", "Hidratos de carbono", "Fibra", "Agua", "Calcio", "Hierro", "Yodo", "Magnesio", "Zinc", "Sodio", "Potasio", "Fósforo", "Selenio", "Tiamina", "Riboflavina", "Vitamina B", "Folatos", "Vitamina B12", "Vitamina C", "Vitamina A", "Vitamina D", "Vitamina E"]));
    let nabo = new Fruit("Nabo", "/imagenes/nabo.jpg", 2.35, "China", "Primavera", "Verdura", "El fruto de las flores es una vaina alargada que mide 2—7 cm de largo la cual guarda las semillas hasta la madurez. La vaina está dividida simétricamente a lo largo de esta y termina en una larga y delgada punta. Esta vaina posee solo una vena prominente que aporta irrigación, a diferencia de otras especies dentro de la familia Brasicaceae las cuales poseen entre 3 a 7 venas. Llegada la madurez la vaina se abre en la mitad para dejar caer las semillas", new Set(["Proteínas", "Hidratos de carbono", "Fibra", "Agua", "Calcio", "Hierro", "Yodo", "Magnesio", "Zinc", "Sodio", "Potasio", "Fósforo", "Selenio", "Tiamina", "Riboflavina", "Vitamina B", "Folatos", "Vitamina B12", "Vitamina C", "Vitamina A", "Vitamina D", "Vitamina E"]));
    let melon = new Fruit("Melón", "/imagenes/melon.jpg", 2.50, "España", "Verano", "Fruta", "Su fruto es una baya pepónide con forma desde esférica hasta elipsoidal. En los llamados melones plátano existen ondulaciones que los hacen parecer una calabaza.", new Set(["Proteínas", "Hidratos de carbono", "Fibra", "Agua", "Calcio", "Hierro", "Yodo", "Magnesio", "Zinc", "Sodio", "Potasio", "Fósforo", "Selenio", "Tiamina", "Riboflavina", "Vitamina B", "Folatos", "Vitamina B12", "Vitamina C", "Vitamina A", "Vitamina D", "Vitamina E"]));

    dataBaseFruits.set(judias.getName(), judias);
    dataBaseFruits.set(calabacin.getName(), calabacin);
    dataBaseFruits.set(calabaza.getName(), calabaza);
    dataBaseFruits.set(nabo.getName(), nabo);
    dataBaseFruits.set(melon.getName(), melon);

    let pepino = new Fruit("Pepino", "/imagenes/pepino.jpg", 2.25, "India", "Primavera", "Fruta", "El pepino es una planta anual, monoica, o sea, que hay flores femeninas y masculinas en el mismo individuo. El tallo es postrado/rastrero, ramificado, anguloso, hirsuto y con zarcillos. Las hojas son delgadas, con pecíolo de 8 cm, con limbo de 12-18 por 11-12 cm, viloso-hispídulo en los nervios y piloso en ambas caras; su contorno es cordado-ovado, tri/penta palmatilobado, con lóbulos triangulares, dentados, acuminados o agudos en el ápice, el mediano de mayor longitud y muy agudo. Las flores masculinas, de 3 estambres, son fasciculadas, con pedicelos de 0,5-2 cm, delgados, híspidos y el receptáculo, con tubo de 8-10 mm, son campanulado o subcilíndrico, densamente viloso, y lóbulos de longitud subigual a la del tubo, lineares, patentes, híspidos; la corola tiene 2-3 cm de diámetro con 5 lóbulos oblongo-lanceolados, agudos. Las flores femeninas son solitarias o fasciculadas, con pedicelo de hasta 2 cm, viloso; el perianto se asemeja al de las flores masculinas. El ovario, de placentación axial es de ordinario fusiforme, cubierto de pelos setiformes, dilatados en la base. El fruto (pepónida), el pepino, de tamaño muy variable, es generalmente oblongo, de cilíndrico a subtrígono, de color verde y esparcidamente tuberculado cuando inmaduro, luego amarillo verdoso y liso. Las semillas de 8-10 por 3-5 mm, son oblongas y blanquecinas.1​ Habitualmente dicho fruto se recolecta aún verde y se consume crudo, o elaborado como encurtido, y entonces se suele denominar pepinillo. La planta tiene una vida vegetal de entre 4 a 5 meses (si a la planta le gusta el ambiente) dando frutos de seguido a partir de los dos meses y medio a tres meses hasta que la planta quede seca por completo.", new Set(["Proteínas", "Hidratos de carbono", "Fibra", "Agua", "Calcio", "Hierro", "Yodo", "Magnesio", "Zinc", "Sodio", "Potasio", "Fósforo", "Selenio", "Tiamina", "Riboflavina", "Vitamina B", "Folatos", "Vitamina B12", "Vitamina C", "Vitamina A", "Vitamina D", "Vitamina E"]));
    let frutaDragon = new Fruit("Fruta del dragón", "/imagenes/frutaDragon.jpg", 4.66, "Centroamérica", "Verano", "Fruta", "La fruta del dragón (o pitahaya) es una planta cactácea, y como tal, resistente a las sequías. La planta es un cactus suculento, rústico, de tallos largos triangulares. Suele enredarse en los árboles próximos alimentándose de la humedad de sus cortezas y trepa por las ramas a ocho o diez metros del suelo sin penetrar en tierra.", new Set(["Agua", "Hierro", "Calcio", "Fósforo", "Vitamina B", "Vitamina C", "Vitamina E", "Fibra"]));

    dataBaseFruits.set(pepino.getName(), pepino);
    dataBaseFruits.set(frutaDragon.getName(), frutaDragon);

    let aguacate = new Fruit("Aguacate", "/imagenes/aguacate.jpg", 2.34, "México", "Invierno", "Fruta", "El fruto es una baya oval o piriforme, según la variedad, de tamaño muy variado (7 a 33 cm de largo y hasta 15 cm de ancho), cáscara de color verde a púrpura oscuro, pudiendo ser delgada, gruesa, lisa o ligeramente rugosa, a veces con una apariencia como la del cuero. Pulpa firme, oleíca, de un color que varía desde el amarillo al verde claro. Contiene una semilla grande (5 a 6,4 cm), dura y pesada, redonda o puntuda, de color marfil. Tiene dos envolturas papelosas de color café, muy delgadas, que a menudo se quedan adheridas a la pulpa.13​ El fruto es generalmente en forma de pera, a veces ovoide o globoso, de 8 a 18cm, con epicarpio corchoso más o menos tuberculado y mesocarpio carnoso y comestible. Este último rodea íntimamente una semilla globular de episperma (tegumento) papiráceo, sin endosperma, de unos 5 a 6cm", new Set(["Proteínas", "Hidratos de carbono", "Fibra", "Agua", "Calcio", "Hierro", "Yodo", "Magnesio", "Zinc", "Sodio", "Potasio", "Fósforo", "Selenio", "Tiamina", "Riboflavina", "Vitamina B", "Folatos", "Vitamina B12", "Vitamina C", "Vitamina A", "Vitamina D", "Vitamina E"]));
    let manzana = new Fruit("Manzana", "/imagenes/manzana.jpg", 2.29, "China", "Otoño", "Fruta", "La manzana procede de un árbol caducifolio, generalmente de 2 a 4,5 m de altura en cultivo y hasta 9 m en la naturaleza. Cuando se cultiva, el tamaño, la forma y la densidad de la rama se determinan mediante el método de selección y recorte de portainjertos. Las hojas, de color verde oscuro, son óvalos simples con márgenes serrados y se inclinan ligeramente hacia abajo; se disponen a lo largo de la rama de forma alterna.", new Set(["Proteínas", "Hidratos de carbono", "Fibra", "Agua", "Calcio", "Hierro", "Yodo", "Magnesio", "Zinc", "Sodio", "Potasio", "Fósforo", "Selenio", "Tiamina", "Riboflavina", "Vitamina B", "Folatos", "Vitamina B12", "Vitamina C", "Vitamina A", "Vitamina D", "Vitamina E"]));
    let sandia = new Fruit("Sandía", "/imagenes/sandia.jpg", 1.79, "Rusia", "Verano", "Fruta", "La sandía, es un fruto de gran tamaño, que se caracteriza por tener una de color verde (oscuro o claro) y amarillo, con o sin listas/rayas. La pulpa es dulce, muy jugosa y refrescante, de color rojo o amarillo, y con semillas negras, marrones o blancas.", new Set(["Proteínas", "Hidratos de carbono ", "Fibra", "Agua", "Calcio", "Hierro", "Yodo", "Magnesio", "Zinc", "Sodio", "Potasio", "Fósforo", "Selenio", "Tiamina", "Riboflavina", "Vitamina B6", "Folatos", "Vitamina B12", "Vitamina C", "Vitamina A: Eq. Retinol", "Vitamina D", "Vitamina E"]))
    let limon = new Fruit("Limón", "/imagenes/limon.jpg", 1.7, "España", "Otoño", "Fruta", "El limón es redondo, ligeramente alargado, posee una corteza fuerte y resistente, es de color amarillo intenso cuando está en plena madurez, brillante que al ser cortada desprende un aroma especial. La pulpa es de color amarillo pálido, jugosa y de sabor ácido dividida en gajos.", new Set(["Proteínas", "Hidratos de carbono", "Fibra", "Agua", "Calcio", "Hierro", "Yodo", "Magnesio", "Zinc", "Sodio", "Potasio", "Fósforo", "Selenio", "Tiamina", "Riboflavina", "Vitamina B", "Folatos", "Vitamina B12", "Vitamina C", "Vitamina A", "Vitamina D", "Vitamina E"]));
    let mandarina = new Fruit("Mandarina", "/imagenes/mandarina.jpg", 1.5, "China", "Otoño", "Fruta", "La mandarina es una fruta que presenta una piel de color amarillo vivo o anaranjado, que es delgada, rugosa y fácilmente despegable de la pulpa. La pulpa está dividida en 10 ó 12 gajos y tiene un sabor dulce agradable, además de ser muy aromática.", new Set(["Vitamina A", "Vitamina C", "Vitamina B6", "Folatos", "Fósforo", "Potasio", "Sodio", "Zinc", "Magnesio", "Hierro", "Calcio", "Agua", "Fibra", "Hidratos de carbono", "Proteinas"]));

    dataBaseFruits.set(aguacate.getName(), aguacate);
    dataBaseFruits.set(manzana.getName(), manzana);
    dataBaseFruits.set(sandia.getName(), sandia);
    dataBaseFruits.set(limon.getName(), limon);
    dataBaseFruits.set(mandarina.getName(), mandarina);
}